# Generated by Django 4.2.7 on 2026-05-03 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_envio', models.CharField(blank=True, max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('estado_envio', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('metodo_pago', models.CharField(default='Tarjeta de Crédito', max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_original', models.DecimalField(blank=True, decimal_places=2, help_text='Precio antes de descuento (opcional)', max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen 2')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen 3')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen 4')),
                ('estrellas', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('num_resenas', models.IntegerField(default=0, verbose_name='Número de reseñas')),
                ('disponible', models.BooleanField(default=True)),
                ('colores', models.CharField(blank=True, help_text='Colores separados por coma: Blanco,Negro,Rosa,Azul', max_length=300)),
                ('tallas', models.CharField(blank=True, help_text='Tallas separadas por coma: XS,S,M,L,XL o 38,39,40,41', max_length=300)),
                ('envio_gratis', models.BooleanField(default=False, verbose_name='Envío gratis')),
                ('meses_sin_intereses', models.IntegerField(default=0, help_text='Número de meses sin intereses (0 = no aplica)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.orden')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.producto')),
            ],
        ),
    ]
